services:
  - type: web
    name: ups-dependencylens-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: PORT
        value: "8080"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"

  - type: web
    name: ups-dependencylens-frontend
    runtime: docker
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    envVars:
      - key: PORT
        value: "80"
